sudo: required
services:
  - docker

before_install:
  - docker build -t rockman25/topsy-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true rockman25/topsy-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "topsy-react"
  env: "TopsyReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-789458539685"
  bucket_path: "topsy-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
